### ISSUE TITLE
Aula 2 no Modelo de Ridge

### ISSUE THREAD

**Issue by renato-campos** [romefeller/predictive#1]
Na criação do modelo Ridge a likelihood não estaria faltando o erro - *eps* ?
como está:
`likelihood = pm.Normal("y_obs",a+b*t,observed=obs_norm)`
como penso que deveria estar:
`likelihood = pm.Normal("y_obs",a+b*t,eps,observed=obs_norm)`

**Comment by romefeller** [comment]
@renato-campos resolvido.
