### ISSUE TITLE
Entrega 1

### ISSUE THREAD

**Issue by romefeller** [romefeller/predictive#2]
Adicionar seu link do repositório/colab aqui. Dê preferência para repositórios.

**Comment by NataliaCFreitas** [comment]
https://colab.research.google.com/drive/1CbypvPJv0t_UbN2fPohH0scmACiEMcSi#scrollTo=LAdxtx9n2q-r&uniqifier=1

**Comment by julerner12** [comment]
https://colab.research.google.com/drive/18HBwNSNyW-_zfxTvIJKP5dpRvLUG7__X?usp=sharing

**Comment by renato-campos** [comment]
[Exercício 1](https://github.com/renato-campos/predictive/blob/main/notebooks/05%20Exerc%C3%ADcio%201%20T-student.ipynb)  [![Abrir no Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/renato-campos/predictive/blob/main/notebooks/05%20Exerc%C3%ADcio%201%20T-student.ipynb)

[Exercício 2](https://github.com/renato-campos/predictive/blob/main/notebooks/05%20Exercício%202.ipynb) [![Abrir no Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/renato-campos/predictive/blob/main/notebooks/05%20Exerc%C3%ADcio%202.ipynb)

**Comment by GuilhermePAmorim** [comment]
https://colab.research.google.com/drive/1HGPhopHHScuhR2Dvth5A3SWDiPz2D50L?usp=sharing

**Comment by Guicamblor** [comment]
[Exercicio1](https://colab.research.google.com/drive/1WV-hLuCcEVeAO2gQX9_AUc4SdwQOP-0w?usp=sharing)
[Exercicio2](https://colab.research.google.com/drive/1yZZDyE5g5S4ixoiJKNLwOMil6H6o9oJ0?usp=sharing)

**Comment by GotinhaJr** [comment]
Aluno: Paulo Alves de Lima Junior

Atividades:
1. [https://colab.research.google.com/drive/13AZqgOqTc3ecCn1vANjgS3fpeJfNU2XN?usp=sharing](url)
2. [https://colab.research.google.com/drive/1Pt5rQEXAPJidK0HJANYlP2T17t4-EajV?usp=sharing](url)

**Comment by GotinhaJr** [comment]
Aulo: Paulo Alves de Lima Junior
Atividades:
1. https://colab.research.google.com/drive/13AZqgOqTc3ecCn1vANjgS3fpeJfNU2XN?usp=sharing
2. https://colab.research.google.com/drive/1Pt5rQEXAPJidK0HJANYlP2T17t4-EajV?usp=sharing

**Comment by juniomuniz** [comment]
Edney Junior Muniz Dos Santos Silva
[SegundoEX](https://colab.research.google.com/drive/12bzbwcefE_Mcz20HP50i7EyqR7SdVU2p?usp=sharing)
[PrimeiroEX](https://colab.research.google.com/drive/1G3Si4gAB7txwsgxGFvs1lf0ep4DTpe3O#scrollTo=1h37Dm6oKZD5)

**Comment by samuel-charadias** [comment]
[https://github.com/samuel-charadias/Teorema-de-Bayes](url)

**Comment by samuel-charadias** [comment]
https://github.com/samuel-charadias/Teorema-de-Bayes/blob/main/Atividade.ipynb

**Comment by dyannacruz** [comment]
Ex1) https://drive.google.com/file/d/1mRHHgdZ12t3pl0JimODJWvceT1RxaOlu/view?usp=sharing
Ex2) https://drive.google.com/file/d/1VsLMb5FXrkQOQ33vWaMMgWLBzOv4kJla/view?usp=sharing

**Comment by romefeller** [comment]
Fim de prazo.
