### ISSUE TITLE
Simulado 1

### ISSUE THREAD

**Issue by romefeller** [romefeller/predictive#4]
1) Taiwanese Bankruptcy (id = 572)

2) Seoul Bike Sharing (id = 560)

**Comment by juniomuniz25** [comment]
1-{Taiwanese Bankruptcy (id = 572)} https://colab.research.google.com/drive/1SCk1xurtL0XOgXYMyfJZkt3RhOcgetvw#scrollTo=0nHTeLVpsSmW
2 -{Seoul Bike Sharing (id = 560)}https://colab.research.google.com/drive/1AI3mkokjJ9b4JCsbzMfeEmU9SEXfCXap#scrollTo=I4Iwt46WWWOC
Edney junior muniz dos santos silva

**Comment by romefeller** [comment]
Prazo
