### ISSUE TITLE
Simulado 1

### ISSUE THREAD

**Issue by romefeller** [romefeller/predictive#9]
Colocar link do github ou colab.

**Comment by gabiduarte435** [comment]
[https://colab.research.google.com/drive/1Rb0cl2UaPjE10fRElv-0yjndT9nDZlWZ#scrollTo=RScNId9tkxKY](url)

**Comment by AnabelleSouza** [comment]
https://colab.research.google.com/drive/1KB5kmjuWAYCfD5hDY-b2HwfSNDX06lY0?usp=sharing

**Comment by gabiduarte435** [comment]
https://colab.research.google.com/drive/1Rb0cl2UaPjE10fRElv-0yjndT9nDZlWZ?usp=sharing

**Comment by namespaiva** [comment]
https://github.com/namespaiva/pred-analysis/blob/main/simulado1.ipynb

**Comment by Diego-Brunetto1010** [comment]
https://colab.research.google.com/drive/1hjOZq2bhO09zN85ZoKd_U8SFTrHXJyEN?usp=sharing

**Comment by gabrielluizone** [comment]
> `ierakika` _(incompleta)_: https://www.kaggle.com/code/gabrielluizone/hierarquica
`ierakiko` _(outro dataset)_: https://drive.google.com/file/d/1e1S3W08gdA7U1qj0OJ4wTJWQY3B76ss-/view?usp=sharing
`logistika`: https://www.kaggle.com/code/gabrielluizone/logistic-regression-bayesian-statistics

**Comment by julianacamara98** [comment]
https://colab.research.google.com/drive/1Ldp4WYUDWs8BATXiXSTR62NRqbLb-w-4#scrollTo=oAyOhRGbmZsq
